### ISSUE TITLE
Crasheo del SV al añadir cuentas

### ISSUE THREAD

**Issue by flvanney** [bnconti/scontable#3]
```
/root/Desktop/scontable/backend/queries.js:25
        if (error) throw error;
                   ^

error: duplicate key value violates unique constraint "cuenta_nro_cta_key"
    at Connection.parseE (/root/Desktop/scontable/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/root/Desktop/scontable/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/root/Desktop/scontable/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)


Solo estaba chusmeando como hacer isues en el GitHub, nada mas
```

**Comment by bnconti** [comment]
Después hace pull y probalo, ahora te debería bloquear el botón si le pones un nombre o nro. que ya está cargado.
